# Generated by Django 2.1.4 on 2019-02-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted',
            field=models.BooleanField(default=False, help_text='If this transaction will be factored in in reports'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Negative amounts indicate expenses, positive indicate income', max_digits=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.ForeignKey(help_text='The associated tag, important for grouping similar transactions for better reporting', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.Tag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Transaction date and time could be set to be different from the date and time of creation of record in the database.'),
        ),
    ]
