# Generated by Django 2.1.4 on 2019-03-17 16:29

import app.core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20190217_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default=app.core.helpers.random_color, max_length=7, null=True),
        ),
    ]
