# Generated by Django 2.1.7 on 2019-03-23 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The end date for this limit.'),
        ),
    ]
