# Generated by Django 2.1.7 on 2019-03-23 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20190323_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The day from which transactions under this tag will countin the limit.'),
        ),
    ]
